### PR TITLE
Restyling of the Micro Services pages

### PR DESCRIPTION
**Pull request by MichelGabriel**
Restyling of the Micro Services pages

**Screenshots after restyling:**

**Collections**

gn-ms-collections

**Items**

gn-ms-items

**Single item**

gn-ms-item

### CODE REVIEW

**Comment by fxprunayre** [comment]
Looks less colored - you don't like gradient ;) At some point we will define what a themes is and apply it here and in GN-UI

For collections, having the short description would be good like in
https://sdi.eea.europa.eu/catalogue/srv/api/sources

Logos don't work or you don't have any in your config ? can be an issue with the link to GN4 also. We will check while merging.

**Comment by MichelGabriel** [comment]
I will have a look at the short description. It looks indeed less coloured, for now I tried to make a simple, basic template to build upon.

The logos are missing because I stopped a harvester when I had enough data on board. It should still be working, but my underlying GeoNetwork just wasn't 100%.

**Comment by MichelGabriel** [comment]
I had a better look at the logos, and somehow there are two `//` in the url that messes it up.

**Comment by fxprunayre** [comment]
> I had a better look at the logos, and somehow there are two `//` in the url that messes it up.

Ok I can have a look into this.

About collections page, maybe we should have same layout as Card view for records so it looks consistent.
https://apps.titellus.net/catalog/gn-ui-material/search/
A collection or harvester are a somehow a "service" metadata record - so quite similar to a record.
We have to create/list those "things" that we want to have similar look in all the application and create style rules for it probably ...

**Comment by MichelGabriel** [comment]
> About collections page, maybe we should have same layout as Card view for records so it looks consistent.

I will restyle it a bit, so it matches. I was already experimenting with it.

**Review by josegar74 — APPROVED** [review]

**Pull request merged**
